<a href="https://colab.research.google.com/github/Mael-zys/SD212/blob/main/lab1_A_sparse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SD212: Graph mining

# Lab 1: Sparse matrices

The objective of this lab is to understand the structure and main properties of [sparse matrices](https://en.wikipedia.org/wiki/Sparse_matrix).

You will learn to code your own sparse matrices to understand their underlying structure. <br>Note that in the other labs, we will only use sparse matrices of [SciPy](https://www.scipy.org/scipylib/index.html). 

## Import

In [ ]:
import numpy as np

In [ ]:
from scipy import sparse

## Coordinate format

In [ ]:
# random matrix (dense format)
A_dense = np.random.randint(2, size = (5,10))

In [ ]:
A_dense

array([[0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [1, 1, 1, 1, 1, 0, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 1, 1, 1, 0, 0, 1, 0, 0]])

In [ ]:
A_coo = sparse.coo_matrix(A_dense)

In [ ]:
A_coo

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 26 stored elements in COOrdinate format>

In [ ]:
A_coo.shape

(5, 10)

In [ ]:
A_coo.nnz

26

In [ ]:
print(A_coo.row)
print(A_coo.col)
print(A_coo.data)

[0 0 0 0 0 0 0 0 0 1 1 2 2 2 2 2 2 3 3 3 3 3 4 4 4 4]
[1 2 3 4 5 6 7 8 9 5 8 0 1 2 3 4 6 1 2 6 8 9 2 3 4 7]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
# there might be zeros in data!
row = A_coo.row
col = A_coo.col
data = np.random.randint(5, size=len(A_coo.data))
shape = A_coo.shape

In [ ]:
shape

(5, 10)

In [ ]:
data

array([2, 1, 2, 2, 0, 4, 3, 4, 2, 1, 2, 3, 4, 3, 3, 1, 0, 2, 2, 0, 3, 1,
       2, 4, 4, 4])

In [ ]:
shape = (3, 5)

indices = [1, 4, 0, 1, 2]

indptr = [0, 2, 2, 5]

data = [1, 3, 1, 2, 1]

In [ ]:
B_coo = sparse.coo_matrix((data, (row, col)), shape)

NameError: ignored

In [ ]:
B_coo

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 26 stored elements in COOrdinate format>

In [ ]:
B_coo.toarray()

array([[0, 2, 1, 2, 2, 0, 4, 3, 4, 2],
       [0, 0, 0, 0, 0, 1, 0, 0, 2, 0],
       [3, 4, 3, 3, 1, 0, 0, 0, 0, 0],
       [0, 2, 2, 0, 0, 0, 0, 0, 3, 1],
       [0, 0, 2, 4, 4, 0, 0, 4, 0, 0]])

In [ ]:
B_coo.nnz

26

In [ ]:
np.sum(B_coo.data > 0)

23

In [ ]:
B_coo.eliminate_zeros()

In [ ]:
B_coo

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 23 stored elements in COOrdinate format>

In [ ]:
B_coo.nnz

20

## To do

Complete the function below that converts a dense matrix into a sparse matrix in COO format. 

Needless to say...
* don't use `scipy`
* don't use any loop

**Hint:** Use `np.nonzero`

In [ ]:
A_dense

array([[0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [1, 1, 1, 1, 1, 0, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 1, 1, 1, 0, 0, 1, 0, 0]])

In [ ]:
np.nonzero(A_dense)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
        4, 4, 4, 4]),
 array([1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 8, 0, 1, 2, 3, 4, 6, 1, 2, 6, 8, 9,
        2, 3, 4, 7]))

In [ ]:
class SparseCOO():
    def __init__(self, data: np.ndarray, row: np.ndarray, col: np.ndarray, shape: tuple):
        self.data = data
        self.row = row
        self.col = col
        self.shape = shape

In [ ]:
def dense_to_coo(A):
    '''Convert dense matrix to sparse in COO format.
    
    Parameters
    ----------
    A : np.ndarray
        Dense matrix
        
    Returns
    -------
    A_coo : SparseCOO
        Sparse matrix in COO format.
    '''
    # to be modified
    data = A[np.nonzero(A)]
    row = np.nonzero(A)[0]
    col = np.nonzero(A)[1] 
    shape = A.shape
    return SparseCOO(data, row, col, shape)

In [ ]:
def test_equality(A, B, attributes):
    return [np.all(getattr(A, a) == getattr(B, a)) for a in attributes]

In [ ]:
# test
A_dense = np.random.randint(2, size = (5,10))
A_coo = sparse.coo_matrix(A_dense)
A_coo_ = dense_to_coo(A_dense)

In [ ]:
test_equality(A_coo, A_coo_, ["data", "row", "col"])

[True, True, True]

## CSR format

The CSR (Compressed Sparse Row) format is the most efficient for arithmetic operations (see below).

In [ ]:
A_dense

array([[0, 0, 0, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 1, 0, 0, 1, 1, 1]])

In [ ]:
A_csr = sparse.csr_matrix(A_dense)

In [ ]:
A_csr

<5x10 sparse matrix of type '<class 'numpy.longlong'>'
	with 23 stored elements in Compressed Sparse Row format>

In [ ]:
A_csr.shape

(5, 10)

In [ ]:
A_csr.nnz

23

In [ ]:
print(A_csr.indices)
print(A_csr.indptr)
print(A_csr.data)

[3 5 6 7 8 9 0 1 7 0 1 2 3 7 9 2 7 9 1 4 7 8 9]
[ 0  6  9 15 18 23]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
A_csr[3, 4]

0

In [ ]:
A_csr[3]

<1x10 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [ ]:
A_csr[3].toarray()

array([[0, 0, 1, 0, 0, 0, 0, 1, 0, 1]])

In [ ]:
# data might have zeros!
indices = A_csr.indices
indptr = A_csr.indptr
data = np.random.randint(5, size=len(A_csr.data))
shape = A_csr.shape

In [ ]:
B_csr = sparse.csr_matrix((data, indices, indptr), shape)

In [ ]:
B_csr

<3x5 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [ ]:
B_csr.nnz

5

In [ ]:
B_csr.toarray()

array([[0, 1, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [1, 2, 1, 0, 0]])

In [ ]:
B_csr.eliminate_zeros()

In [ ]:
B_csr

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [ ]:
# from COO format
row = [0, 0, 1, 2, 2]
col = [2, 3, 0, 1, 2]
data = np.ones(5)
A_csr = sparse.csr_matrix((data, (row, col)), shape = (3, 4))

In [ ]:
A_csr.toarray()

array([[0., 0., 1., 1.],
       [1., 0., 0., 0.],
       [0., 1., 1., 0.]])

In [ ]:
# equivalently
A_coo = sparse.coo_matrix((data, (row, col)), shape = (3, 4))
A_csr = sparse.csr_matrix(A_coo)

In [ ]:
A_csr.toarray()

array([[0., 0., 1., 1.],
       [1., 0., 0., 0.],
       [0., 1., 1., 0.]])

## To do

Complete the function below that converts a sparse matrix from COO format to CSR format.

Again...
* don't use `scipy`
* don't use any loop

**Hint:** Use ``np.unique`` and ``np.cumsum``.

In [ ]:
class SparseCSR():
    def __init__(self, data: np.ndarray, indices: np.ndarray, indptr: np.ndarray, shape: tuple):
        self.data = data
        self.indices = indices
        self.indptr = indptr
        self.shape = shape

In [ ]:
def coo_to_csr(A_coo):
    '''Convert a sparse matrix from COO to CSR format.
    
    Parameters
    ----------
    A_coo : SparseCSR
        Sparse matrix in COO format.
        
    Returns
    -------
    A_csr : SparseCSR
        Sparse matrix in CSR format.
    '''
    # to be modified
    data = A_coo.data
    indices = A_coo.col
    shape = A_coo.shape
    indptr = np.zeros(shape[0] + 1, dtype = int)
    row_indices, counts = np.unique(A_coo.row, return_counts=True)
    print(row_indices)
    print(counts)
    indptr[row_indices+1] = counts
    indptr = np.cumsum(indptr)
    return SparseCSR(data, indices, indptr, shape)

In [ ]:
def dense_to_csr(A):
    '''Convert dense matrix to sparse in CSR format.
    
    Parameters
    ----------
    A : np.ndarray
        Dense matrix
        
    Returns
    -------
    A_csr : SparseCSR
        Sparse matrix in CSR format.
    '''
    return coo_to_csr(sparse.coo_matrix(A))

In [ ]:
# test
A_dense = np.random.randint(2, size = (5,10))
A_csr = sparse.csr_matrix(A_dense)
A_csr_ = dense_to_csr(A_dense)
print(A_csr.indptr)
print(A_csr_.indptr)

[0 1 2 3 4]
[2 5 5 6 6]
[ 0  2  7 12 18 24]
[ 0  2  7 12 18 24]


In [ ]:
test_equality(A_csr, A_csr_, ["data", "indices", "indptr"])

[True, True, True]

## Diagonal format

In [ ]:
A_diag = sparse.diags(np.arange(5))

In [ ]:
A_diag

In [ ]:
A_diag.toarray()

In [ ]:
A_diag.diagonal()

In [ ]:
A = sparse.csr_matrix(A_diag)

In [ ]:
A

## To do

Complete the following function that returns a sparse CSR matrix with the pseudo-inverse vector on the diagonal.

**Example:** pseudo inverse of (0, 1, 2) -> (0, 1, 1/2)

**Hint:** Use the property of sparse matrices!

In [ ]:
def get_pseudo_inverse(vector):
    '''Return a sparse matrix with pseudo-inverse on the diagonal.
    
    Parameters
    ----------
    vector : np.ndarray
        Input vector. 
        
    Returns
    -------
    A_csr : sparse.csr_matrix
        Sparse matrix in scipy CSR format.
    '''    
    # to be modified
    return None

In [ ]:
# test
get_pseudo_inverse(np.arange(3))

## Operations

Usual arithmetic operations apply to sparse matrices. The only contraint is to have a sparse matrix on the **left-hand side** of the operator.

In [ ]:
A = sparse.csr_matrix(A_dense)

In [ ]:
n_row, n_col = A.shape

In [ ]:
A.dot(np.ones(n_col, dtype=int))

In [ ]:
A.T.dot(np.ones(n_row, dtype=int))

In [ ]:
# observe the format of the transpose
A.T

In [ ]:
A.T.dot(A)

In [ ]:
A.dot(A.T)

In [ ]:
A.data = np.random.choice((1,2,3,4), size = len(A.data))

In [ ]:
B = A > 1

In [ ]:
B

In [ ]:
# Explain the following warning...
B = A < 1

In [ ]:
B

In [ ]:
B_dense = np.random.randint(2, size = (5,10))
B = sparse.csr_matrix(B_dense)

In [ ]:
2 * A + 5 * B

## To do

Complete the following function that normalizes a sparse CSR matrix with non-negative entries so that each row sums to 1 (or to 0 if the whole row is zero). 

**Hint:** Use the above function ``get_pseudo_inverse``.

In [ ]:
def normalize_rows(A):
    '''Normalize the rows of a CSR matrix so that all sum to 1 (or 0).
    
    Parameters
    ----------
    A : sparse.csr_matrix
        Input matrix (non-negative entries).
    
    Returns
    -------
    A_norm : sparse.csr_matrix
        Normalized matrix. 
    
    '''
    # to be modified
    return None

## To do

Complete the following method that returns the dot product of a sparse CSR matrix with a vector.

* No loop allowed!

In [ ]:
class SparseCSR():
    def __init__(self, data: np.ndarray, indices: np.ndarray, indptr: np.ndarray, shape: tuple):
        self.data = data
        self.indices = indices
        self.indptr = indptr
        self.shape = shape
        
    def dot(self, x: np.ndarray) -> np.ndarray:
        '''Sparse-vector dot product.'''
        # to be modified
        return None

## Slicing

Sparse matrices can be sliced like numpy arrays. The CSR format is more efficient for row slicing (although column slicing is possible), while the CSC format is more efficient for column slicing.

In [ ]:
A = sparse.csr_matrix(A_dense)

In [ ]:
A[:2]

In [ ]:
A[1:4,2:]

In [ ]:
A[np.array([0,2,4])]

## To do 

Consider the following matrix:

In [ ]:
A = sparse.csr_matrix(np.random.randint(2, size = (20,30)))

Extract the 10 rows of largest sums and build the corresponding matrix.

## Bonus

Complete all methods of the following CSR class.

In [ ]:
class SparseCSR():
    def __init__(self, data: np.ndarray, indices: np.ndarray, indptr: np.ndarray, shape: tuple):
        self.data = data
        self.indices = indices
        self.indptr = indptr
        self.shape = shape
        
    def dot(self, x: np.ndarray) -> np.ndarray:
        '''Sparse-vector dot product.'''
        # to be modified
        return None

    def dot_array(self, X: np.ndarray) -> np.ndarray:
        '''Sparse-array dot product.'''
        # to be modified
        return None
    
    def dot_sparse(self, X: SparseCSR) -> SparseCSR:
        '''Sparse-sparse dot product.'''
        # to be modified
        return None
    
    def add_sparse(self, X: SparseCSR) -> SparseCSR:
        '''Add a sparse matrix.'''
        # to be modified
        return None
    
    def slice_row(self, index: np.ndarray) -> SparseCSR:
        '''Slice rows of a sparse matrix.'''
        # to be modified
        return None
    
    def slice_col(self, index: np.ndarray) -> SparseCSR:
        '''Slice columns of a sparse matrix.'''
        # to be modified
        return None
    
    def eliminate_zeros(self) -> SparseCSR:
        '''Eliminate zeros of a sparse matrix.'''
        # to be modified
        return None